/**
 * Downloads the webfonts we actually use and writes a local @font-face sheet.
 *
 * Self-hosting rather than linking Google Fonts buys three things measured in
 * this project:
 *   1. Removes a cross-origin round trip that cost ~700ms on throttled mobile.
 *   2. Lets the critical faces be <link rel=preload>ed by exact URL, which a
 *      Google Fonts stylesheet cannot (its file URLs are versioned and change).
 *   3. Kills the font-swap reflow that showed up as 0.07 CLS on the home page,
 *      because the real face now arrives before first paint instead of after.
 *
 *   npm run fonts:fetch
 */
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = path.join(ROOT, 'apps', 'web', 'public', 'fonts');
// Written to public/ rather than src/styles so it stays OUT of the bundled,
// render-blocking app stylesheet — index.html loads it asynchronously.
const CSS_OUT = path.join(ROOT, 'apps', 'web', 'public', 'fonts.css');

// A modern Chrome UA is required or Google serves ttf instead of woff2.
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

interface Family {
  /** Google Fonts family spec. */
  spec: string;
  /** Local filename stem. */
  stem: string;
  /** Unicode ranges to keep — everything else is dropped. */
  keep: RegExp;
}

const FAMILIES: Family[] = [
  { spec: 'Cormorant+Garamond:wght@300;400;500', stem: 'cormorant', keep: /latin|latin-ext/ },
  { spec: 'Inter:wght@400;500;600', stem: 'inter', keep: /latin|latin-ext|cyrillic/ },
  { spec: 'Noto+Serif+Armenian:wght@300;400;500', stem: 'noto-serif-am', keep: /armenian|latin/ },
  { spec: 'Noto+Sans+Armenian:wght@400;500', stem: 'noto-sans-am', keep: /armenian|latin/ },
];

interface Face {
  family: string;
  weight: string;
  style: string;
  unicodeRange: string;
  url: string;
  subset: string;
}

/** Google's CSS is emitted as `/* subset *\/ @font-face { ... }` blocks. */
function parseFaces(css: string): Face[] {
  const faces: Face[] = [];
  const blocks = css.split('/*').slice(1);

  for (const block of blocks) {
    const subset = block.slice(0, block.indexOf('*/')).trim();
    const family = /font-family:\s*'([^']+)'/.exec(block)?.[1];
    const weight = /font-weight:\s*(\d+)/.exec(block)?.[1] ?? '400';
    const style = /font-style:\s*(\w+)/.exec(block)?.[1] ?? 'normal';
    const url = /src:\s*url\(([^)]+)\)/.exec(block)?.[1];
    const unicodeRange = /unicode-range:\s*([^;]+);/.exec(block)?.[1]?.trim() ?? '';
    if (family && url) faces.push({ family, weight, style, unicodeRange, url, subset });
  }
  return faces;
}

async function main(): Promise<void> {
  await mkdir(OUT_DIR, { recursive: true });

  const declarations: string[] = [
    '/* GENERATED by scripts/fetch-fonts.ts — do not edit by hand.',
    '   Run `npm run fonts:fetch` to refresh. */',
    '',
  ];
  let downloaded = 0;
  let skipped = 0;

  for (const family of FAMILIES) {
    const cssUrl = `https://fonts.googleapis.com/css2?family=${family.spec}&display=swap`;
    const css = await (await fetch(cssUrl, { headers: { 'User-Agent': UA } })).text();
    const faces = parseFaces(css);

    for (const face of faces) {
      if (!family.keep.test(face.subset)) {
        skipped += 1;
        continue;
      }
      const name = `${family.stem}-${face.weight}-${face.subset}.woff2`;
      const bytes = Buffer.from(await (await fetch(face.url)).arrayBuffer());
      await writeFile(path.join(OUT_DIR, name), bytes);
      downloaded += 1;

      declarations.push(
        '@font-face {',
        `  font-family: "${face.family}";`,
        `  font-style: ${face.style};`,
        `  font-weight: ${face.weight};`,
        // swap, not optional: Armenian text must never silently fall back to a
        // face without Armenian glyphs.
        '  font-display: swap;',
        `  src: url("/fonts/${name}") format("woff2");`,
        ...(face.unicodeRange ? [`  unicode-range: ${face.unicodeRange};`] : []),
        '}',
        '',
      );
    }
  }

  await writeFile(CSS_OUT, declarations.join('\n'));
  console.log(`✔ ${downloaded} woff2 files → apps/web/public/fonts (${skipped} subsets skipped)`);
  console.log('✔ @font-face sheet → apps/web/public/fonts.css');
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
